# Generated by Django 4.2.5 on 2023-11-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211104_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
