# Generated by Django 4.2.5 on 2023-11-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_characteristic1_product_characteristic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.TextField(blank=True),
        ),
    ]
